const WEATHER_CURRENT_PATH = import.meta.env.VITE_WEATHER_CURRENT_PATH;
const WEATHER_FORECAST_PATH = import.meta.env.VITE_WEATHER_FORECAST_PATH;

export const API_URLS = {
  WEATHER_CURRENT: `${WEATHER_CURRENT_PATH}`,
  WEATHER_FORECAST: `${WEATHER_FORECAST_PATH}`,
};
